


project_id = "hmztritmqsscxnjhrvqi"

# Business Update Processing Functions
[functions.process-update-with-template]
enabled = true
verify_jwt = true
import_map = "./functions/_shared/import_map.json"
entrypoint = "./functions/process-update-with-template/index.ts"

[functions.publish-pages]
enabled = true
verify_jwt = true
import_map = "./functions/_shared/import_map.json"  
entrypoint = "./functions/publish-pages/index.ts"

[functions.get-page-analytics]
enabled = true
verify_jwt = true
import_map = "./functions/_shared/import_map.json"
entrypoint = "./functions/get-page-analytics/index.ts"
